api = "0.4"

[buildpack]
id = "digitalocean/apt"
version = "0.0.2"
name = "apt Packages Buildpack"
homepage = "https://github.com/digitalocean/buildpack-apt"
description = "Installs apt packages for further builds and runtime"
keywords = ["apt", "packages", "ubuntu"]

[[buildpack.licenses]]
type = "MIT"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "heroku-22"

[[stacks]]
id = "io.buildpacks.stacks.jammy"
